/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;


import java.awt.Dimension;
import java.sql.*;
import javax.swing.JOptionPane;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author INDIA
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        switchPanels(AdminHome);
        
        EmployerComplaintsPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        EmployerComplaintsPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        InternComplaintsPane.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        InternComplaintsPane.getVerticalScrollBar().setUnitIncrement(16);
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        employerOnInterns = new javax.swing.JButton();
        internsOnEmployers = new javax.swing.JButton();
        AdminPane = new javax.swing.JLayeredPane();
        AdminHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AdminEmployer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmployerComplaintsPane1 = new javax.swing.JScrollPane();
        panelProduct1 = new javax.swing.JPanel();
        AdminIntern = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        InternComplaintsPane = new javax.swing.JScrollPane();
        panelProduct = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 223, 227));

        jPanel1.setBackground(new java.awt.Color(49, 87, 94));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(49, 87, 94));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Out");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INlogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 808, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(441, 441, 441)
                    .addComponent(jLabel12)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel12)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(70, 124, 134));

        button1.setBackground(new java.awt.Color(70, 124, 134));
        button1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Home");
        button1.setBorder(null);
        button1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        employerOnInterns.setBackground(new java.awt.Color(70, 124, 134));
        employerOnInterns.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        employerOnInterns.setForeground(new java.awt.Color(255, 255, 255));
        employerOnInterns.setText("Employer Complaints");
        employerOnInterns.setBorder(null);
        employerOnInterns.setMargin(new java.awt.Insets(0, 0, 0, 0));
        employerOnInterns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employerOnInternsActionPerformed(evt);
            }
        });

        internsOnEmployers.setBackground(new java.awt.Color(70, 124, 134));
        internsOnEmployers.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        internsOnEmployers.setForeground(new java.awt.Color(255, 255, 255));
        internsOnEmployers.setText("Intern Complaints");
        internsOnEmployers.setBorder(null);
        internsOnEmployers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        internsOnEmployers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internsOnEmployersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(employerOnInterns, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internsOnEmployers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(employerOnInterns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(internsOnEmployers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AdminHome.setBackground(new java.awt.Color(202, 223, 227));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Home");

        javax.swing.GroupLayout AdminHomeLayout = new javax.swing.GroupLayout(AdminHome);
        AdminHome.setLayout(AdminHomeLayout);
        AdminHomeLayout.setHorizontalGroup(
            AdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHomeLayout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(357, 357, 357))
        );
        AdminHomeLayout.setVerticalGroup(
            AdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHomeLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(260, 260, 260))
        );

        AdminEmployer.setBackground(new java.awt.Color(202, 223, 227));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 87, 94));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employer Complaint list");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmployerComplaintsPane1.setBackground(new java.awt.Color(215, 231, 234));
        EmployerComplaintsPane1.setBorder(null);
        EmployerComplaintsPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelProduct1.setBackground(new java.awt.Color(202, 223, 227));
        panelProduct1.setLayout(new java.awt.GridBagLayout());
        EmployerComplaintsPane1.setViewportView(panelProduct1);

        javax.swing.GroupLayout AdminEmployerLayout = new javax.swing.GroupLayout(AdminEmployer);
        AdminEmployer.setLayout(AdminEmployerLayout);
        AdminEmployerLayout.setHorizontalGroup(
            AdminEmployerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminEmployerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
            .addGroup(AdminEmployerLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(EmployerComplaintsPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        AdminEmployerLayout.setVerticalGroup(
            AdminEmployerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminEmployerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmployerComplaintsPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AdminIntern.setBackground(new java.awt.Color(202, 223, 227));
        AdminIntern.setPreferredSize(new java.awt.Dimension(1024, 576));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 87, 94));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Intern Complaint list");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        InternComplaintsPane.setBackground(new java.awt.Color(202, 223, 227));
        InternComplaintsPane.setBorder(null);
        InternComplaintsPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelProduct.setBackground(new java.awt.Color(202, 223, 227));
        panelProduct.setLayout(new java.awt.GridBagLayout());
        InternComplaintsPane.setViewportView(panelProduct);

        javax.swing.GroupLayout AdminInternLayout = new javax.swing.GroupLayout(AdminIntern);
        AdminIntern.setLayout(AdminInternLayout);
        AdminInternLayout.setHorizontalGroup(
            AdminInternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminInternLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(AdminInternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminInternLayout.createSequentialGroup()
                        .addComponent(InternComplaintsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminInternLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342))))
        );
        AdminInternLayout.setVerticalGroup(
            AdminInternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminInternLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InternComplaintsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AdminPane.setLayer(AdminHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AdminPane.setLayer(AdminEmployer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AdminPane.setLayer(AdminIntern, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AdminPaneLayout = new javax.swing.GroupLayout(AdminPane);
        AdminPane.setLayout(AdminPaneLayout);
        AdminPaneLayout.setHorizontalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminEmployer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminIntern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminPaneLayout.setVerticalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminEmployer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminIntern, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminPane)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminPane))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
        {
            dispose();
            Welcome wel = new Welcome();
            wel.setVisible(true);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        switchPanels(AdminHome);
        button1.setEnabled(false);
        employerOnInterns.setEnabled(true);
        internsOnEmployers.setEnabled(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void employerOnInternsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employerOnInternsActionPerformed
        // TODO add your handling code here:
        switchPanels(AdminEmployer);
        button1.setEnabled(true);
        employerOnInterns.setEnabled(false);
        internsOnEmployers.setEnabled(true);
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "santosh","oracle");

            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM EMPLOYER_REPORTS");
            ResultSet rs = pstmt.executeQuery();

            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(3,0,3,0);
            //System.out.println(rs.);
            int i=0;
            while(rs.next())
            {
                String internshipId = rs.getString(3);
                pstmt = con.prepareStatement("SELECT INTERNSHIPNAME FROM INTERNSHIP_DETAILS WHERE INTERNSHIPID=?");
                pstmt.setString(1,internshipId);
                ResultSet rs1 = pstmt.executeQuery();
                
                rs1.next();
                
                gbc.gridx = 0;
                gbc.gridy = i++;
                panelProduct1.add(new adminEmpOnIntComplaintPanel(rs.getString(1),rs.getString(2),internshipId,rs.getString(4),rs1.getString(1),this),gbc);
//                panelProduct1.add(new EmployerIntershipList(String.valueOf('1'),i),gbc);
                
                panelProduct1.repaint();
                panelProduct1.revalidate();
                EmployerComplaintsPane1.revalidate();
            }
            
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_employerOnInternsActionPerformed

    public void refreshEmployerReports()
    {
        panelProduct1.removeAll();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "santosh","oracle");

            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM EMPLOYER_REPORTS");
            ResultSet rs = pstmt.executeQuery();

            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(3,0,3,0);
            //System.out.println(rs.);
            int i=0;
            while(rs.next())
            {
                String internshipId = rs.getString(3);
                pstmt = con.prepareStatement("SELECT INTERNSHIPNAME FROM INTERNSHIP_DETAILS WHERE INTERNSHIPID=?");
                pstmt.setString(1,internshipId);
                ResultSet rs1 = pstmt.executeQuery();
                
                rs1.next();
                
                gbc.gridx = 0;
                gbc.gridy = i++;
                panelProduct1.add(new adminEmpOnIntComplaintPanel(rs.getString(1),rs.getString(2),internshipId,rs.getString(4),rs1.getString(1),this),gbc);
                
                panelProduct1.repaint();
                panelProduct1.revalidate();
                EmployerComplaintsPane1.revalidate();
            }
            
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void internsOnEmployersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internsOnEmployersActionPerformed
        // TODO add your handling code here:
        switchPanels(AdminIntern);
        button1.setEnabled(true);
        employerOnInterns.setEnabled(true);
        internsOnEmployers.setEnabled(false);
        
        panelProduct.removeAll();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "santosh","oracle");

            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_REPORTS");
            ResultSet rs = pstmt.executeQuery();
            
            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(3,0,3,0);
            int i=0;
            while(rs.next())
            {
                String internshipId = rs.getString(3);
                pstmt = con.prepareStatement("SELECT INTERNSHIPNAME FROM INTERNSHIP_DETAILS WHERE INTERNSHIPID=?");
                pstmt.setString(1,internshipId);
                ResultSet rs1 = pstmt.executeQuery();
                
                rs1.next();
                
                gbc.gridx = 0;
                gbc.gridy = i++;
                panelProduct.add(new adminIntOnEmpComplaintPanel(rs.getString(1),rs.getString(2),internshipId,rs.getString(4),rs1.getString(1),this),gbc);
                
                panelProduct.repaint();
                panelProduct.revalidate();
                InternComplaintsPane.revalidate();
            }
            
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_internsOnEmployersActionPerformed

    public void refreshInternReports()
    {
        panelProduct.removeAll();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "santosh","oracle");

            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_REPORTS");
            ResultSet rs = pstmt.executeQuery();

            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(3,0,3,0);
            int i=0;
            while(rs.next())
            {
                String internshipId = rs.getString(3);
                pstmt = con.prepareStatement("SELECT INTERNSHIPNAME FROM INTERNSHIP_DETAILS WHERE INTERNSHIPID=?");
                pstmt.setString(1,internshipId);
                ResultSet rs1 = pstmt.executeQuery();
                
                rs1.next();
                
                gbc.gridx = 0;
                gbc.gridy = i++;
                panelProduct.add(new adminIntOnEmpComplaintPanel(rs.getString(1),rs.getString(2),internshipId,rs.getString(4),rs1.getString(1),this),gbc);
                
                panelProduct.repaint();
                panelProduct.revalidate();
                InternComplaintsPane.revalidate();
            }
            
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }
    
    public void switchPanels(javax.swing.JPanel panel)
    {
        AdminPane.removeAll();
        AdminPane.add(panel);
        AdminPane.repaint();
        AdminPane.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminEmployer;
    private javax.swing.JPanel AdminHome;
    private javax.swing.JPanel AdminIntern;
    private javax.swing.JLayeredPane AdminPane;
    private javax.swing.JScrollPane EmployerComplaintsPane1;
    private javax.swing.JScrollPane InternComplaintsPane;
    private javax.swing.JButton button1;
    private javax.swing.JButton employerOnInterns;
    private javax.swing.JButton internsOnEmployers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelProduct;
    private javax.swing.JPanel panelProduct1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
