/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;

import java.awt.Color;

/**
 *
 * @author INDIA
 */
public class adminIntOnEmpComplaintPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminEmpIntComplaintPanel
     */
    
    public String employerId = "";
    public String internId = "";
    public String internshipId = "";
    public String description = "";
    public String internshipName = "";
    AdminHome ah;
//    public adminEmpOnIntComplaintPanel() {
//        initComponents();
//    }
    
    public adminIntOnEmpComplaintPanel(String employerId, String internId,String internshipId,String description,String internshipName,AdminHome ah) {
        initComponents();
        
        this.employerId = employerId;
        this.internId = internId;
        this.internshipId= internshipId;
        this.internshipName = internshipName;
        this.description = description;
        this.ah = ah;
        
        employerNameComplaint.setText(employerId);
        internNameComplaint.setText(internId);
        InternshipIdComplaint.setText(internshipId);
        internshipNameComplaint.setText(internshipName);
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        internNameComplaint = new javax.swing.JLabel();
        InternshipIdComplaint = new javax.swing.JLabel();
        employerNameComplaint = new javax.swing.JLabel();
        viewMore = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        internshipNameComplaint = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setText("Complaint On: ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 124, 134));
        jLabel3.setText("By               :");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 124, 134));
        jLabel4.setText("Internship ID:");

        internNameComplaint.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internNameComplaint.setForeground(new java.awt.Color(70, 124, 134));
        internNameComplaint.setText("Naveen");

        InternshipIdComplaint.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        InternshipIdComplaint.setForeground(new java.awt.Color(70, 124, 134));
        InternshipIdComplaint.setText("VCE");

        employerNameComplaint.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        employerNameComplaint.setForeground(new java.awt.Color(49, 87, 94));
        employerNameComplaint.setText("Santosh");

        viewMore.setBackground(new java.awt.Color(244, 139, 1));
        viewMore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewMore.setForeground(new java.awt.Color(255, 255, 255));
        viewMore.setText("View More");
        viewMore.setBorder(null);
        viewMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMoreMouseExited(evt);
            }
        });
        viewMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 124, 134));
        jLabel5.setText("Internship Name:");

        internshipNameComplaint.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internshipNameComplaint.setForeground(new java.awt.Color(70, 124, 134));
        internshipNameComplaint.setText("VCE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(InternshipIdComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(internshipNameComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(employerNameComplaint, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internNameComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(193, 193, 193)
                        .addComponent(viewMore, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employerNameComplaint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(internNameComplaint)
                    .addComponent(viewMore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(InternshipIdComplaint))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(internshipNameComplaint)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoreActionPerformed
        // TODO add your handling code here:
        InternReportDetails ird = new InternReportDetails(employerId,internId,internshipId,description,internshipName,ah);
        ird.setVisible(true);

        
    }//GEN-LAST:event_viewMoreActionPerformed

    private void hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover
      // TODO add your handling code here:
    }//GEN-LAST:event_hover

    private void viewMoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMoreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMoreMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InternshipIdComplaint;
    private javax.swing.JLabel employerNameComplaint;
    private javax.swing.JLabel internNameComplaint;
    private javax.swing.JLabel internshipNameComplaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton viewMore;
    // End of variables declaration//GEN-END:variables
}
