/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
/**
 *
 * @author INDIA
 */
public class ApplicationStatus extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationStatus
     */
    
    public ApplicationStatus() {
        initComponents();
        pleaseContact.setVisible(false);
        contactPhoneNumber.setVisible(false);
        contactEmailId.setVisible(false);
        
        internshipName.setDisabledTextColor(Color.GRAY);
        internshipCategory.setDisabledTextColor(Color.GRAY);
        internshipLocation.setDisabledTextColor(Color.GRAY);  
        internshipReqSkills.setDisabledTextColor(Color.GRAY);
        internshipSalary.setDisabledTextColor(Color.GRAY);
        internshipPeriod.setDisabledTextColor(Color.GRAY);
        internshipWorkplace.setDisabledTextColor(Color.GRAY);
                       
        setIconImage();
    }
    public void setStatusValues(String internshipId,String status){
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_DETAILS WHERE internshipid = ?");
            
            pstmt.setString(1,internshipId);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next())
            {
                internshipName.setText(rs.getString(2));
                internshipCategory.setText(rs.getString(4));
                internshipLocation.setText(rs.getString(5));      
                internshipSalary.setText(rs.getString(6));
                internshipPeriod.setText(rs.getString(8));
                internshipWorkplace.setText(rs.getString(9));
                //System.out.println(rs.getString(2));
            }
            pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_REQSKILLS WHERE INTERNSHIPID = ?");
            pstmt.setString(1,internshipId);
            ResultSet rs1 = pstmt.executeQuery();
            String skills = "";
            while(rs1.next())
            {
                skills = skills + rs1.getString(2) + ", ";
            }
            internshipReqSkills.setText(skills);
            internshipReqSkills.setToolTipText(skills);
                        
            PreparedStatement pstmt1 = con.prepareStatement("SELECT * FROM EMPLOYER_DETAILS WHERE USERNAME = (SELECT USERNAME FROM EMPLOYER_INTERNSHIPS WHERE INTERNSHIPID = ?)");
            pstmt1.setString(1,internshipId);
            rs1 = pstmt1.executeQuery();
            rs1.next();
            
            statusValue.setText(status);
            if(status.equals("SELECTED"))
            {   
                statusValue.setForeground(Color.GREEN);
                statusMessage.setText("Congratulations, you have been selected for this particular internship");
                
                contactPhoneNumber.setText(rs1.getString(7));
                contactEmailId.setText(rs1.getString(8));
                pleaseContact.setVisible(true);
                contactPhoneNumber.setVisible(true);
                contactEmailId.setVisible(true);
            }
                
            else if(status.equals("REJECTED"))
            {
                statusValue.setForeground(Color.RED);
                statusMessage.setText("Your application has been rejected, keep trying!");
            }
            else if(status.equals("PENDING"))
            {
                statusValue.setForeground(Color.YELLOW);
                statusMessage.setText("Your application is in verification stage");
            }
            else if(status.equals("COMPLETED"))
            {    
                statusValue.setForeground(Color.BLUE);
                statusMessage.setText("Congratulations, you have successfully completed this internship");
            }
            contactEmailId.setToolTipText(contactEmailId.getText());
            statusValue.setText(status);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        internshipName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        internshipCategory = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        internshipReqSkills = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        internshipSalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        internshipPeriod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        internshipWorkplace = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        statusMessage = new javax.swing.JLabel();
        pleaseContact = new javax.swing.JLabel();
        contactPhoneNumber = new javax.swing.JLabel();
        contactEmailId = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        statusValue = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        internshipLocation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(215, 231, 234));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(49, 87, 94));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Application Status");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 87, 94));
        jLabel8.setText("INTERNSHIP NAME        :");

        internshipName.setEnabled(false);
        internshipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipNameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 87, 94));
        jLabel12.setText("CATEGORY                    :");

        internshipCategory.setEnabled(false);
        internshipCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipCategoryActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 87, 94));
        jLabel9.setText("REQUIRED SKILLS         :");

        internshipReqSkills.setEnabled(false);
        internshipReqSkills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipReqSkillsActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 87, 94));
        jLabel10.setText("SALARY/STIPEND         :");

        internshipSalary.setEnabled(false);
        internshipSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipSalaryActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(49, 87, 94));
        jLabel7.setText("PERIOD                       :");

        internshipPeriod.setEnabled(false);
        internshipPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipPeriodActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 87, 94));
        jLabel13.setText("WORK FROM             :");

        internshipWorkplace.setEnabled(false);
        internshipWorkplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipWorkplaceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setText("STATUS             :");

        statusMessage.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        statusMessage.setForeground(new java.awt.Color(49, 87, 94));
        statusMessage.setText("Congratulations, you have been selected for this particular internship");

        pleaseContact.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        pleaseContact.setForeground(new java.awt.Color(49, 87, 94));
        pleaseContact.setText("Please contact:");

        contactPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        contactPhoneNumber.setForeground(new java.awt.Color(49, 87, 94));
        contactPhoneNumber.setText("01987329371");

        contactEmailId.setBackground(new java.awt.Color(255, 255, 255));
        contactEmailId.setForeground(new java.awt.Color(49, 87, 94));
        contactEmailId.setText("asdasfdasdfsaf");

        jButton1.setBackground(new java.awt.Color(244, 139, 1));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        statusValue.setBackground(new java.awt.Color(255, 255, 255));
        statusValue.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        statusValue.setForeground(new java.awt.Color(0, 204, 0));
        statusValue.setText("ACCEPTED");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(statusValue)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusValue)
        );

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(49, 87, 94));
        jLabel14.setText("LOCATION             :");

        internshipLocation.setEnabled(false);
        internshipLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(internshipName, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipReqSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(247, 247, 247))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pleaseContact)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contactPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(contactEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(statusMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98))
                                .addComponent(internshipLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel22)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipReqSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pleaseContact, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internshipCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipCategoryActionPerformed

    private void internshipReqSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipReqSkillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipReqSkillsActionPerformed

    private void internshipPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipPeriodActionPerformed

    private void internshipSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipSalaryActionPerformed

    private void internshipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipNameActionPerformed

    private void internshipWorkplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipWorkplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipWorkplaceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void internshipLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipLocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactEmailId;
    private javax.swing.JLabel contactPhoneNumber;
    private javax.swing.JTextField internshipCategory;
    private javax.swing.JTextField internshipLocation;
    private javax.swing.JTextField internshipName;
    private javax.swing.JTextField internshipPeriod;
    private javax.swing.JTextField internshipReqSkills;
    private javax.swing.JTextField internshipSalary;
    private javax.swing.JTextField internshipWorkplace;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pleaseContact;
    private javax.swing.JLabel statusMessage;
    private javax.swing.JLabel statusValue;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
