/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author INDIA
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    String internshipId;
    String internId;
    public Application(String internshipId,String internId) {
        initComponents();
        this.internshipId = internshipId;
        this.internId = internId;
        
        internshipName.setDisabledTextColor(Color.GRAY);
        InternshipVacancies.setDisabledTextColor(Color.GRAY);
        internshipCategory.setDisabledTextColor(Color.GRAY);
        internshipLocation.setDisabledTextColor(Color.GRAY);
        internshipSalary.setDisabledTextColor(Color.GRAY);
        internshipEndDate.setDisabledTextColor(Color.GRAY);
        internshipPeriod.setDisabledTextColor(Color.GRAY);
        internshipWorkplace.setDisabledTextColor(Color.GRAY);
        internshipReqSkills.setDisabledTextColor(Color.GRAY);
                
        setIconImage();
    }
    
    public void setInternshipDetails(String internshipId){
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_DETAILS WHERE internshipid = ?");
            pstmt.setString(1,internshipId);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next())
            {
                internshipName.setText(rs.getString(2));
                InternshipVacancies.setText(rs.getString(3));
                internshipCategory.setText(rs.getString(4));
                internshipLocation.setText(rs.getString(5));
                internshipSalary.setText(rs.getString(6));
                internshipEndDate.setText(rs.getString(7));
                internshipPeriod.setText(rs.getString(8));
                internshipWorkplace.setText(rs.getString(9));
            }
            pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_REQSKILLS WHERE INTERNSHIPID = ?");
            pstmt.setString(1,internshipId);
            ResultSet rs1 = pstmt.executeQuery();
            String skills = "";
            while(rs1.next())
            {
                skills = skills + rs1.getString(2) + ", ";
            }
            internshipReqSkills.setText(skills);
            internshipReqSkills.setToolTipText(skills);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        internshipName = new javax.swing.JTextField();
        InternshipVacancies = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        internshipCategory = new javax.swing.JTextField();
        internshipWorkplace = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        internshipReqSkills = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        internshipPeriod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        internshipSalary = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        internshipLocation = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        internshipEndDate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        applyInternshipButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(215, 231, 234));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(49, 87, 94));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("INTERNSHIP DETAILS");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 87, 94));
        jLabel8.setText("NAME                            :");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 87, 94));
        jLabel6.setText("VACANCIES                :");

        internshipName.setEnabled(false);
        internshipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipNameActionPerformed(evt);
            }
        });

        InternshipVacancies.setEnabled(false);
        InternshipVacancies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternshipVacanciesActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 87, 94));
        jLabel12.setText("CATEGORY                    :");

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 87, 94));
        jLabel13.setText("WORK FROM             :");

        internshipCategory.setEnabled(false);
        internshipCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipCategoryActionPerformed(evt);
            }
        });

        internshipWorkplace.setEnabled(false);
        internshipWorkplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipWorkplaceActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 87, 94));
        jLabel9.setText("REQUIRED SKILLS         :");

        internshipReqSkills.setEnabled(false);
        internshipReqSkills.setMaximumSize(new java.awt.Dimension(6, 22));
        internshipReqSkills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipReqSkillsActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(49, 87, 94));
        jLabel7.setText("PERIOD                       :");

        internshipPeriod.setEnabled(false);
        internshipPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipPeriodActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 87, 94));
        jLabel10.setText("SALARY/STIPEND         :");

        internshipSalary.setEnabled(false);
        internshipSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipSalaryActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 87, 94));
        jLabel11.setText("LOCATION              :");

        internshipLocation.setEnabled(false);
        internshipLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipLocationActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(49, 87, 94));
        jLabel14.setText("END DATE FOR APPLICATION       :");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setText("EMPLOYER PROFILE       :");

        internshipEndDate.setForeground(new java.awt.Color(204, 204, 204));
        internshipEndDate.setEnabled(false);
        internshipEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipEndDateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(244, 139, 1));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        applyInternshipButton.setBackground(new java.awt.Color(244, 139, 1));
        applyInternshipButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        applyInternshipButton.setForeground(new java.awt.Color(255, 255, 255));
        applyInternshipButton.setText("Apply");
        applyInternshipButton.setBorder(null);
        applyInternshipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyInternshipButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(244, 139, 1));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(applyInternshipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(internshipName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(internshipReqSkills, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(internshipSalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(internshipEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internshipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(internshipWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(jLabel6)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)
                                .addComponent(InternshipVacancies)
                                .addComponent(internshipLocation)
                                .addComponent(internshipPeriod)
                                .addComponent(jLabel1)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipReqSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InternshipVacancies, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internshipLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(internshipEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyInternshipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internshipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipNameActionPerformed

    private void InternshipVacanciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternshipVacanciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InternshipVacanciesActionPerformed

    private void internshipReqSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipReqSkillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipReqSkillsActionPerformed

    private void internshipPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipPeriodActionPerformed

    private void internshipLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipLocationActionPerformed

    private void internshipSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipSalaryActionPerformed

    private void internshipEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipEndDateActionPerformed

    private void internshipCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipCategoryActionPerformed

    private void internshipWorkplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipWorkplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipWorkplaceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            SelectedEmployerProfile emp = new SelectedEmployerProfile();
            emp.setVisible(true);
            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM EMPLOYER_DETAILS WHERE username=(SELECT username FROM EMPLOYER_INTERNSHIPS WHERE internshipId=?)");
            pstmt.setString(1,internshipId);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next())
            {
                emp.setEmployerDesignation(rs.getString(3));
                emp.setEmployerExperience(rs.getString(5));
                emp.setEmployerName(rs.getString(2));
                emp.setEmployerOrganisation(rs.getString(4));
                emp.setEmployerImage(rs.getString(1));
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void applyInternshipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyInternshipButtonActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_ENROLLED_INTERNS WHERE INTERNSHIPID=? AND INTERNID=?");
            pstmt.setString(1,this.internshipId);
            pstmt.setString(2,this.internId);
            ResultSet rs1 = pstmt.executeQuery();
            
            if(rs1.next())
            {
                JOptionPane.showMessageDialog(this, "You have already applied for this internship !");
                flag = 1;
            }
            
            if(flag == 0)
            {
                pstmt = con.prepareStatement("INSERT INTO INTERNSHIP_ENROLLED_INTERNS VALUES(?,?,?)");
                pstmt.setString(1,this.internshipId);
                pstmt.setString(2, this.internId);
                pstmt.setString(3, "PENDING");
                int rs = pstmt.executeUpdate();
                if(rs > 0)
                {
                    JOptionPane.showMessageDialog(this, "THANK YOU FOR APPLYING !");
                    dispose();
                }
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_applyInternshipButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Application().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InternshipVacancies;
    private javax.swing.JButton applyInternshipButton;
    private javax.swing.JTextField internshipCategory;
    private javax.swing.JTextField internshipEndDate;
    private javax.swing.JTextField internshipLocation;
    private javax.swing.JTextField internshipName;
    private javax.swing.JTextField internshipPeriod;
    private javax.swing.JTextField internshipReqSkills;
    private javax.swing.JTextField internshipSalary;
    private javax.swing.JTextField internshipWorkplace;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
