/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;

import java.sql.*;
import javax.swing.*;
    
/**
 *
 * @author INDIA
 */
public class ApplicantPanel extends javax.swing.JPanel {
//    public String InternName = "";
//    public String InternRating = "";
//    public String InternQualification = "";
//    public String InternSkills = "";
//    public int id;
//    /**
//     * Creates new form ApplicantPanel
//     */
    public String internId;
    public String internshipId;
    ApplicantsList al;
    EmployerHome eh;
    public ApplicantPanel(String internId,String internshipId,ApplicantsList al,EmployerHome eh) {
        initComponents();
        this.internId = internId;
        this.internshipId = internshipId;
        this.al = al;
        this.eh = eh;
        setApplicantsDetails(this.internId);
    }
    
    public void setApplicantsDetails(String internId)
    {
        internImage.setText("");
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,internId);
            ResultSet rs = pstmt.executeQuery();
            rs.next();
            internName.setText(rs.getString(2));
            internRating.setText(rs.getString(5));
            internQualification.setText(rs.getString(4));
            
            Blob b = rs.getBlob(8);
            byte barr[]= b.getBytes(1,(int)b.length());
			              
            ImageIcon icon = new ImageIcon(barr);
            java.awt.Image img = icon.getImage();
            //System.out.println(internImage.getWidth());
            java.awt.Image scale = img.getScaledInstance(90, 90,java.awt.Image.SCALE_SMOOTH);
            ImageIcon scaled = new ImageIcon(scale);
            internImage.setIcon(scaled);
            
            pstmt = con.prepareStatement("SELECT * FROM INTERN_SKILLS WHERE INTERNID = ?");
            pstmt.setString(1,internId);
            ResultSet rs1 = pstmt.executeQuery();
            String skills = "";
            while(rs1.next())
            {
                skills = skills + rs1.getString(2) + ", ";
            }
            internSkills.setText(skills);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        internRating = new javax.swing.JLabel();
        internQualification = new javax.swing.JLabel();
        internSkills = new javax.swing.JLabel();
        viewInternProfileButton = new javax.swing.JButton();
        internImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        internName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        internName.setForeground(new java.awt.Color(49, 87, 94));
        internName.setText("Name");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 124, 134));
        jLabel1.setText("Intern Rating   :");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 124, 134));
        jLabel2.setText("Qualification    :");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 124, 134));
        jLabel3.setText("Skills                  :");

        internRating.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internRating.setForeground(new java.awt.Color(70, 124, 134));
        internRating.setText("Rating");

        internQualification.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internQualification.setForeground(new java.awt.Color(70, 124, 134));
        internQualification.setText("-");

        internSkills.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internSkills.setForeground(new java.awt.Color(70, 124, 134));
        internSkills.setText("-");

        viewInternProfileButton.setBackground(new java.awt.Color(244, 139, 1));
        viewInternProfileButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        viewInternProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        viewInternProfileButton.setText("View More");
        viewInternProfileButton.setBorder(null);
        viewInternProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInternProfileButtonActionPerformed(evt);
            }
        });

        internImage.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        internImage.setForeground(new java.awt.Color(49, 87, 94));
        internImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internImage.setText("IMAGE");
        internImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 87, 94)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(internSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(internRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(internQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(internName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(viewInternProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(internName)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(internRating))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(internQualification)))
                    .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(internSkills)
                .addGap(18, 18, 18)
                .addComponent(viewInternProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInternProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInternProfileButtonActionPerformed
        // TODO add your handling code here:
        String viewIntern;
        SelectedInternProfile internDetails = new SelectedInternProfile(al,eh);
        internDetails.setVisible(true);
        
        
        //internDetails.setInternSkills(internSkills);
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,internId);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next())
            {
                internDetails.setInternAge(rs.getString(3));
                internDetails.setInternContactNumber(rs.getString(6));
                internDetails.setInternEmailId(rs.getString(7));
                internDetails.setInternName(rs.getString(2));
                internDetails.setInternQualification(rs.getString(4));
                internDetails.setInternRating(rs.getString(5));
                internDetails.setInternUsername(rs.getString(1));
                internDetails.setInternshipId(this.internshipId);
                
                //rs.getString(8);
            }
            pstmt = con.prepareStatement("SELECT * FROM INTERN_SKILLS WHERE INTERNID = ?");
            pstmt.setString(1,internId);
            rs = pstmt.executeQuery();
            String skills = "";
            while(rs.next())
            {
                skills = skills + rs.getString(2) + ", ";
            }
            internDetails.setInternSkills(skills);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        } 
        
    }//GEN-LAST:event_viewInternProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel internImage;
    private javax.swing.JLabel internName;
    private javax.swing.JLabel internQualification;
    private javax.swing.JLabel internRating;
    private javax.swing.JLabel internSkills;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton viewInternProfileButton;
    // End of variables declaration//GEN-END:variables
}
