/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author INDIA
 */
public class ApplicantsList extends javax.swing.JFrame {

    /**
     * Creates new form ApplicantsList
     */
    public String internshipId;
    public String internName;
    public String internRating;
    public String qualification;
    public  String internId;
    EmployerHome eh;
    public ApplicantsList(String internshipId,EmployerHome eh) {
        initComponents();
        this.internshipId = internshipId;
        this.eh = eh;
        
        ApplicantListPane.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        ApplicantListPane.getVerticalScrollBar().setUnitIncrement(16);
        //setApplicantsDetails(internshipId);
        setIconImage();
    }
    
    public void setApplicantsDetails(String internshipId)
    {

        getPanelProduct1().removeAll();
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"PENDING");
            ResultSet rs = pstmt.executeQuery();
            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(4,4,4,4);
            int i=0;
            int j=0;
            while(rs.next())
            {
                internId = rs.getString(1);
                gbc.gridx = i%2;
                gbc.gridy = j;
                //getPanelProduct1().add(new ApplicantPanel(internId),gbc);
                getPanelProduct1().add(new ApplicantPanel(internId,this.internshipId,this,eh),gbc);
                
                getPanelProduct1().repaint();
                getPanelProduct1().revalidate();
                getApplicantListPane().revalidate();
                if(i%2 == 1)
                    j++;
                i++;
            }
            
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        searchApplicants = new javax.swing.JButton();
        selectedRating = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ApplicantListPane = new javax.swing.JScrollPane();
        panelProduct1 = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(215, 231, 234));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Applicants' List");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        searchApplicants.setBackground(new java.awt.Color(244, 139, 1));
        searchApplicants.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        searchApplicants.setForeground(new java.awt.Color(255, 255, 255));
        searchApplicants.setText("Search");
        searchApplicants.setBorder(null);
        searchApplicants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchApplicantsActionPerformed(evt);
            }
        });

        selectedRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "InternRating (Low to High)", "InternRating (High to Low)" }));
        selectedRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedRatingActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 87, 94));
        jLabel3.setText("Sort By  :");

        ApplicantListPane.setBorder(null);
        ApplicantListPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelProduct1.setBackground(new java.awt.Color(202, 223, 227));
        panelProduct1.setLayout(new java.awt.GridBagLayout());
        ApplicantListPane.setViewportView(panelProduct1);

        applyButton.setBackground(new java.awt.Color(244, 139, 1));
        applyButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        applyButton.setForeground(new java.awt.Color(255, 255, 255));
        applyButton.setText("Apply");
        applyButton.setBorder(null);
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(302, 302, 302))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedRating, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ApplicantListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchApplicants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectedRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBox))
                .addGap(17, 17, 17)
                .addComponent(ApplicantListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void searchApplicantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchApplicantsActionPerformed
        // TODO add your handling code here:
        
        int flag1=0,flag2=0;
        panelProduct1.removeAll();
        String search = searchBox.getText();
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE USERNAME IN (SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid =? AND applicationstatus=?) AND (NAME LIKE ? OR INTERNRATING LIKE ? OR QUALIFICATION LIKE ?)");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"PENDING");
            pstmt.setString(3,"%"+search+"%");
            pstmt.setString(4,"%"+search+"%");
            pstmt.setString(5,"%"+search+"%");
            ResultSet rs = pstmt.executeQuery();
            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            
            gbc.insets = new Insets(4,4,4,4);

            int i=0;
            int j=0;
            
            while(rs.next())
            {
                flag1 = 1;
                internId = rs.getString(1);
                gbc.gridx = i%2;
                gbc.gridy = j;
                //getPanelProduct1().add(new ApplicantPanel(internId),gbc);
                getPanelProduct1().add(new ApplicantPanel(internId,this.internshipId,this,eh),gbc);
                
                getPanelProduct1().repaint();
                getPanelProduct1().revalidate();
                getApplicantListPane().revalidate();
                if(i%2 == 1)
                    j++;
                i++;
            }
            pstmt = con.prepareStatement("SELECT INTERNID FROM INTERN_SKILLS WHERE INTERNID IN (SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?) AND SKILLS LIKE ?");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"PENDING");
            pstmt.setString(3,search);
//            pstmt.setString(3,"%"+search+"%");
            rs = pstmt.executeQuery();
            
            gbc.insets = new Insets(4,4,4,4);
            int k = 0;
            int l = 0;
            while(rs.next())
            {
                flag2 = 1;
                internId = rs.getString(1);
                gbc.gridx = k%2;
                gbc.gridy = l;
                //getPanelProduct1().add(new ApplicantPanel(internId),gbc);
                getPanelProduct1().add(new ApplicantPanel(internId,this.internshipId,this,eh),gbc);
                
                getPanelProduct1().repaint();
                getPanelProduct1().revalidate();
                getApplicantListPane().revalidate();
                if(k%2 == 1)
                    l++;
                k++;
            }
            if(i==0)
            {
                panelProduct1.removeAll();
                panelProduct1.add(new NoResultsFoundPanel());
                panelProduct1.repaint();
                panelProduct1.revalidate();
                getApplicantListPane().revalidate();
            }
            
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
        
    }//GEN-LAST:event_searchApplicantsActionPerformed

    private void selectedRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedRatingActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:
        
        getPanelProduct1().removeAll();
        String selRating = selectedRating.getItemAt(selectedRating.getSelectedIndex());
        String userId;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            PreparedStatement pstmt;// = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE USERNAME IN (SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?) ORDER BY INTERNRATING ASC");
            if(selRating.equals("InternRating (Low to High)"))
            {
                pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE USERNAME IN (SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?) ORDER BY INTERNRATING ASC");
                
            }
            else if(selRating.equals("InternRating (High to Low)"))
            {
                pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE USERNAME IN (SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?) ORDER BY INTERNRATING DESC");
            }
            else{
                pstmt = con.prepareStatement("SELECT INTERNID FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND applicationstatus=?");
            }
            
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"PENDING");
            ResultSet rs = pstmt.executeQuery();
            java.awt.GridBagConstraints gbc = new GridBagConstraints();
            
            gbc.insets = new Insets(4,4,4,4);
            int i = 0;
            int j = 0;
            while(rs.next())
            {
                userId = rs.getString(1);
                gbc.gridx = i%2;
                gbc.gridy = j;
                //getPanelProduct1().add(new ApplicantPanel(internId),gbc);
                getPanelProduct1().add(new ApplicantPanel(userId,internshipId,this,eh),gbc);
                getPanelProduct1().repaint();
                getPanelProduct1().revalidate();
                getApplicantListPane().revalidate();
                if(i%2 == 1)
                    j++;
                i++;
            }
            if(i==0)
            {
                getPanelProduct1().removeAll();
                getPanelProduct1().add(new NoResultsFoundPanel());
                getPanelProduct1().repaint();
                getPanelProduct1().revalidate();
                getApplicantListPane().revalidate();
            }
        con.close();
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ApplicantsList().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ApplicantListPane;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JButton searchApplicants;
    private javax.swing.JTextField searchBox;
    private javax.swing.JComboBox<String> selectedRating;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JPanel getPanelProduct1() {
        return panelProduct1;
    }

    /**
     * @param panelProduct1 the panelProduct1 to set
     */
    public void setPanelProduct1(javax.swing.JPanel panelProduct1) {
        this.panelProduct1 = panelProduct1;
    }

    /**
     * @return the ApplicantListPane
     */
    public javax.swing.JScrollPane getApplicantListPane() {
        return ApplicantListPane;
    }

    /**
     * @param ApplicantListPane the ApplicantListPane to set
     */
    public void setApplicantListPane(javax.swing.JScrollPane ApplicantListPane) {
        this.ApplicantListPane = ApplicantListPane;
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }

}

