/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;
import java.awt.GridBagConstraints;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author INDIA
 */
public class EmployerIntershipList extends javax.swing.JPanel {

    /**
     * Creates new form EmployerIntershipList
     */
    public String internshipId;
    public String row;
    EmployerHome eh;
    public EmployerIntershipList(String internshipId,EmployerHome eh) {
        initComponents();
        this.row = String.valueOf(row);
        this.internshipId = internshipId;
        this.eh = eh;
        setInternshipDetails(this.internshipId);
        
    }
    
    public void setInternshipDetails(String internshipId)
    {
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERNSHIP_DETAILS WHERE internshipid = ?");
            pstmt.setString(1,internshipId);
            ResultSet rs = pstmt.executeQuery();
            rs.next();
            internshipName.setText(rs.getString(2));
            endDate.setText(rs.getString(7).substring(0,10));
            
            pstmt = con.prepareStatement("SELECT count(*) FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid = ? AND APPLICATIONSTATUS=?");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"PENDING");
            rs = pstmt.executeQuery();
            rs.next();
            
            int noApps = rs.getInt("count(*)");
            
            
            pstmt = con.prepareStatement("SELECT count(*) FROM INTERNSHIP_ENROLLED_INTERNS WHERE internshipid=? and applicationstatus = ?");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,"SELECTED");
            rs = pstmt.executeQuery();
            rs.next();
            int selApps = rs.getInt("count(*)");
            noOfSelectedInterns.setText(String.valueOf(selApps));
            noOfApplications.setText(String.valueOf(noApps));
            
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internshipName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noOfApplications = new javax.swing.JLabel();
        enrolledApplicantsList = new javax.swing.JButton();
        selectedInterns = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        noOfSelectedInterns = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        internshipName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        internshipName.setForeground(new java.awt.Color(49, 87, 94));
        internshipName.setText("Name");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 124, 134));
        jLabel3.setText("No. of Applications:");

        noOfApplications.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        noOfApplications.setForeground(new java.awt.Color(70, 124, 134));
        noOfApplications.setText("5");

        enrolledApplicantsList.setBackground(new java.awt.Color(244, 139, 1));
        enrolledApplicantsList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enrolledApplicantsList.setForeground(new java.awt.Color(255, 255, 255));
        enrolledApplicantsList.setText("Applicants List");
        enrolledApplicantsList.setBorder(null);
        enrolledApplicantsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolledApplicantsListActionPerformed(evt);
            }
        });

        selectedInterns.setBackground(new java.awt.Color(244, 139, 1));
        selectedInterns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectedInterns.setForeground(new java.awt.Color(255, 255, 255));
        selectedInterns.setText("Selected Interns");
        selectedInterns.setBorder(null);
        selectedInterns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedInternsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 124, 134));
        jLabel5.setText("Selected Interns    :");

        noOfSelectedInterns.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        noOfSelectedInterns.setForeground(new java.awt.Color(70, 124, 134));
        noOfSelectedInterns.setText("5");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 124, 134));
        jLabel2.setText("Last date :");

        endDate.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        endDate.setForeground(new java.awt.Color(70, 124, 134));
        endDate.setText("dd-mm-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noOfApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noOfSelectedInterns, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(internshipName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enrolledApplicantsList, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedInterns, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(endDate))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(internshipName)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(noOfApplications)
                    .addComponent(jLabel5)
                    .addComponent(noOfSelectedInterns)
                    .addComponent(enrolledApplicantsList, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedInterns, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void selectedInternsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedInternsActionPerformed
        // TODO add your handling code here:
        SelectedInternsList selectedList = new SelectedInternsList(this.internshipId);
        selectedList.setSelectedInternsDetails(this.internshipId);
        selectedList.setVisible(true);
    }//GEN-LAST:event_selectedInternsActionPerformed

    private void enrolledApplicantsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolledApplicantsListActionPerformed
        // TODO add your handling code here:
        ApplicantsList applications = new ApplicantsList(this.internshipId,eh);
        applications.setApplicantsDetails(this.internshipId);
        applications.setVisible(true);
    }//GEN-LAST:event_enrolledApplicantsListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endDate;
    private javax.swing.JButton enrolledApplicantsList;
    private javax.swing.JLabel internshipName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel noOfApplications;
    private javax.swing.JLabel noOfSelectedInterns;
    private javax.swing.JButton selectedInterns;
    // End of variables declaration//GEN-END:variables
}
