/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author INDIA
 */
public class EmployerReportDetails extends javax.swing.JFrame {

    /**
     * Creates new form ReportDetails
     */
    public String employerId = "";
    public String internId = "";
    public String internshipId = "";
    public String Description = "";
    public String internshipName = "";
    AdminHome ah;
    
    public EmployerReportDetails(String employerId, String internId,String internshipId,String description,String internshipName,AdminHome ah)
    {
        
        initComponents();
        
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        this.employerId = employerId;
        this.internId = internId;
        this.internshipId= internshipId;
        this.internshipName = internshipName;
        this.Description = description;
        this.ah = ah;
        
        reportInternUsername.setText(internId);
        reportInternshipId.setText(internshipId);
        reportDescription.setText(Description);
        
        reportInternUsername.setDisabledTextColor(Color.GRAY);
        reportInternshipId.setDisabledTextColor(Color.GRAY);
        reportDescription.setDisabledTextColor(Color.GRAY);
        
        setIconImage();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reportInternUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        reportInternshipId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportDescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        reportEmployerProfile = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        reportInternProfile = new javax.swing.JButton();
        deleteReport = new javax.swing.JButton();
        deleteIntern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(215, 231, 234));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(49, 87, 94));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("EMPLOYER REPORT DETAILS");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 87, 94));
        jLabel8.setText("INTERN USERNAME                    :");

        reportInternUsername.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        reportInternUsername.setForeground(new java.awt.Color(49, 87, 94));
        reportInternUsername.setEnabled(false);
        reportInternUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportInternUsernameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 87, 94));
        jLabel9.setText("INTERNSHIP ID                        :");

        reportInternshipId.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        reportInternshipId.setForeground(new java.awt.Color(49, 87, 94));
        reportInternshipId.setEnabled(false);
        reportInternshipId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportInternshipIdActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 87, 94));
        jLabel11.setText("REPORT DESCRIPTION             :");

        reportDescription.setColumns(20);
        reportDescription.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        reportDescription.setForeground(new java.awt.Color(49, 87, 94));
        reportDescription.setRows(5);
        reportDescription.setEnabled(false);
        jScrollPane1.setViewportView(reportDescription);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 87, 94));
        jLabel12.setText("EMPLOYER PROFILE                :");

        reportEmployerProfile.setBackground(new java.awt.Color(244, 139, 1));
        reportEmployerProfile.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        reportEmployerProfile.setForeground(new java.awt.Color(255, 255, 255));
        reportEmployerProfile.setText("View");
        reportEmployerProfile.setBorder(null);
        reportEmployerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportEmployerProfileActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 87, 94));
        jLabel13.setText("INTERN PROFILE                     :");

        reportInternProfile.setBackground(new java.awt.Color(244, 139, 1));
        reportInternProfile.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        reportInternProfile.setForeground(new java.awt.Color(255, 255, 255));
        reportInternProfile.setText("View");
        reportInternProfile.setBorder(null);
        reportInternProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportInternProfileActionPerformed(evt);
            }
        });

        deleteReport.setBackground(new java.awt.Color(244, 139, 1));
        deleteReport.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        deleteReport.setForeground(new java.awt.Color(255, 255, 255));
        deleteReport.setText("DELETE REPORT");
        deleteReport.setBorder(null);
        deleteReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReportActionPerformed(evt);
            }
        });

        deleteIntern.setBackground(new java.awt.Color(244, 139, 1));
        deleteIntern.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        deleteIntern.setForeground(new java.awt.Color(255, 255, 255));
        deleteIntern.setText("DELETE INTERN");
        deleteIntern.setBorder(null);
        deleteIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInternActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(deleteReport, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(reportInternUsername)
                                .addComponent(reportInternshipId)
                                .addComponent(jScrollPane1)
                                .addComponent(reportEmployerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reportInternProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(reportInternUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(reportInternshipId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(reportEmployerProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(reportInternProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteReport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reportInternshipIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportInternshipIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportInternshipIdActionPerformed

    private void reportEmployerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportEmployerProfileActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            SelectedEmployerProfile emp = new SelectedEmployerProfile();
            emp.setVisible(true);
            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM EMPLOYER_DETAILS WHERE username=(SELECT username FROM EMPLOYER_INTERNSHIPS WHERE internshipId=?)");
            pstmt.setString(1,internshipId);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next())
            {
                emp.setEmployerDesignation(rs.getString(3));
                emp.setEmployerExperience(rs.getString(5));
                emp.setEmployerName(rs.getString(2));
                emp.setEmployerOrganisation(rs.getString(4));
                emp.setEmployerImage(rs.getString(1));
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_reportEmployerProfileActionPerformed

    private void reportInternUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportInternUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportInternUsernameActionPerformed

    private void reportInternProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportInternProfileActionPerformed
        // TODO add your handling code here:
        String viewIntern;
        ViewCertifyInternProfile internDetails = new ViewCertifyInternProfile(this.internId);
        internDetails.setVisible(true);
        
        
        //internDetails.setInternSkills(internSkills);
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,internId);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next())
            {
                internDetails.setInternAge(rs.getString(3));
                internDetails.setInternContactNumber(rs.getString(6));
                internDetails.setInternEmailId(rs.getString(7));
                internDetails.setInternName(rs.getString(2));
                internDetails.setInternQualification(rs.getString(4));
                internDetails.setInternRating(rs.getString(5));
                internDetails.setInternUsername(rs.getString(1));
            }
            pstmt = con.prepareStatement("SELECT * FROM INTERN_SKILLS WHERE INTERNID = ?");
            pstmt.setString(1,internId);
            rs = pstmt.executeQuery();
            String skills = "";
            while(rs.next())
            {
                skills = skills + rs.getString(2) + ", ";
            }
            internDetails.setInternSkills(skills);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);} 
    }//GEN-LAST:event_reportInternProfileActionPerformed

    private void deleteInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInternActionPerformed
        // TODO add your handling code here:
        
        //delete intern in intern_details table
        int a = JOptionPane.showConfirmDialog(this,"Are you sure to delete this intern?");  
        if(a == JOptionPane.YES_OPTION){  
            try{  
                Class.forName("oracle.jdbc.driver.OracleDriver");  

                Connection con = DriverManager.getConnection(  
                "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

                PreparedStatement pstmt = con.prepareStatement("DELETE FROM INTERN_LOGIN WHERE USERNAME=?");
                pstmt.setString(1,this.internId);
                int rs = pstmt.executeUpdate();

                pstmt = con.prepareStatement("DELETE FROM INTERN_DETAILS WHERE USERNAME=?");
                pstmt.setString(1,this.internId);
                int rs2 = pstmt.executeUpdate();

                pstmt = con.prepareStatement("DELETE FROM INTERNSHIP_ENROLLED_INTERNS WHERE INTERNID=)");
                pstmt.setString(1,this.internId);
                int rs3 = pstmt.executeUpdate();

                pstmt = con.prepareStatement("DELETE FROM INTERNSHIP_INTERNRATING WHERE INTERNID=?");
                pstmt.setString(1,this.internId);
                int rs4 = pstmt.executeUpdate();
                
                pstmt = con.prepareStatement("DELETE FROM INTERN_SKILLS WHERE INTERNID=?");
                pstmt.setString(1,this.internId);
                int rs5 = pstmt.executeUpdate();

                pstmt = con.prepareStatement("DELETE FROM INTERN_REPORTS WHERE INTERNID=?");
                pstmt.setString(1,this.internId);
                int rs6 = pstmt.executeUpdate();

                if(rs>0 && rs2>0 && rs3>0 && rs4>0 && rs5>0 && rs6>0)
                {
                    JOptionPane.showMessageDialog(this,"Successfully deleted the intern");
                    dispose();
                    ah.refreshEmployerReports();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Problem occured while deleting the intern");
                    dispose();
                }
            con.close();  
            }
            catch(Exception e){ 
                System.out.println(e);}
        }
    }//GEN-LAST:event_deleteInternActionPerformed

    private void deleteReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReportActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            
            PreparedStatement pstmt = con.prepareStatement("DELETE FROM EMPLOYER_REPORTS WHERE EMPLOYERID=? AND INTERNID=? AND INTERNSHIPID=?");
            pstmt.setString(1,employerId);
            pstmt.setString(2,internId);
            pstmt.setString(3,internshipId);
            int rs = pstmt.executeUpdate();
                    
            if(rs>0)
            {
                JOptionPane.showMessageDialog(this,"Successfully deleted the report");
                dispose();
                ah.refreshEmployerReports();
            }
            else{
                JOptionPane.showMessageDialog(this,"Problem occured while deleting the report");
                dispose();
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);} 
        //delete report from employer_reports table
    }//GEN-LAST:event_deleteReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EmployerReportDetails().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteIntern;
    private javax.swing.JButton deleteReport;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportDescription;
    private javax.swing.JButton reportEmployerProfile;
    private javax.swing.JButton reportInternProfile;
    private javax.swing.JTextField reportInternUsername;
    private javax.swing.JTextField reportInternshipId;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
