/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author INDIA
 */
public class EmployerCertifyInterns extends javax.swing.JFrame {

    /**
     * Creates new form EmployerCertifyInterns
     */
    String internId;
    String internshipId;
    SelectedInternsList sil;
    public EmployerCertifyInterns(String internId) {
        initComponents();
        this.internId = internId;
        
        internName.setDisabledTextColor(Color.GRAY);
        internUsername.setDisabledTextColor(Color.GRAY);
        setIconImage();
    }
    
    public void setInternName(String Name) {
        internName.setText(Name);
    }
    
    public void setInternUsername(String Username) {
        internUsername.setText(Username);
    }
    public void setInternshipId(String internshipId){
        this.internshipId = internshipId;
    }
    
    public void setRefreshFrame(SelectedInternsList sil)
    {
        this.sil = sil;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        internName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        internUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkInternProfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        certifyIntern = new javax.swing.JButton();
        internRating = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(215, 231, 234));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Intern Certification");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 87, 94));
        jLabel3.setText("Intern Name         :");

        internName.setEditable(false);
        internName.setForeground(new java.awt.Color(49, 87, 94));
        internName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 87, 94));
        jLabel4.setText("Intern Username   :");

        internUsername.setEditable(false);
        internUsername.setForeground(new java.awt.Color(49, 87, 94));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 87, 94));
        jLabel5.setText("Intern Profile        :");

        checkInternProfile.setBackground(new java.awt.Color(244, 139, 1));
        checkInternProfile.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        checkInternProfile.setForeground(new java.awt.Color(255, 255, 255));
        checkInternProfile.setText("Click");
        checkInternProfile.setBorder(null);
        checkInternProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInternProfileActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 87, 94));
        jLabel2.setText("Rating                 :");

        certifyIntern.setBackground(new java.awt.Color(244, 139, 1));
        certifyIntern.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        certifyIntern.setForeground(new java.awt.Color(255, 255, 255));
        certifyIntern.setText("Certify");
        certifyIntern.setBorder(null);
        certifyIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certifyInternActionPerformed(evt);
            }
        });

        internRating.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        internRating.setForeground(new java.awt.Color(49, 87, 94));
        internRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        internRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internRatingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkInternProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(internUsername)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(certifyIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(internUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkInternProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(certifyIntern, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internRatingActionPerformed

    private void internNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internNameActionPerformed

    private void certifyInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certifyInternActionPerformed
        // TODO add your handling code here:
       
        // set status to complete and add rating to table
        String rating = internRating.getItemAt(internRating.getSelectedIndex());
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            
            PreparedStatement pstmt = con.prepareStatement("INSERT INTO INTERNSHIP_INTERNRATING VALUES(?,?,?)");
            pstmt.setString(1,internshipId);
            pstmt.setString(2,internId);
            pstmt.setString(3,rating);
            int rs = pstmt.executeUpdate();
            
            pstmt = con.prepareStatement("UPDATE INTERNSHIP_ENROLLED_INTERNS SET APPLICATIONSTATUS=? WHERE INTERNSHIPID=? AND INTERNID=?");
            pstmt.setString(1,"COMPLETED");
            pstmt.setString(2,internshipId);
            pstmt.setString(3,internId);
            rs = pstmt.executeUpdate();
            
            pstmt = con.prepareStatement("UPDATE INTERN_DETAILS SET INTERNRATING=(SELECT AVG(RATING) FROM INTERNSHIP_INTERNRATING WHERE INTERNID=?) WHERE  USERNAME=?");
            pstmt.setString(1,internId);
            pstmt.setString(2,internId);
            rs = pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "CERTIFICATION COMPLETED !");
            dispose();
            sil.setSelectedInternsDetails(internshipId);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        } 
        
    }//GEN-LAST:event_certifyInternActionPerformed

    private void checkInternProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInternProfileActionPerformed
        // TODO add your handling code here:
        String viewIntern;
        ViewCertifyInternProfile internDetails = new ViewCertifyInternProfile(this.internId);
        internDetails.setVisible(true);
        
        
        //internDetails.setInternSkills(internSkills);
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,internId);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next())
            {
                internDetails.setInternAge(rs.getString(3));
                internDetails.setInternContactNumber(rs.getString(6));
                internDetails.setInternEmailId(rs.getString(7));
                internDetails.setInternName(rs.getString(2));
                internDetails.setInternQualification(rs.getString(4));
                internDetails.setInternRating(rs.getString(5));
                internDetails.setInternUsername(rs.getString(1));
                //rs.getString(8);
            }
            pstmt = con.prepareStatement("SELECT * FROM INTERN_SKILLS WHERE INTERNID = ?");
            pstmt.setString(1,internId);
            rs = pstmt.executeQuery();
            String skills = "";
            while(rs.next())
            {
                skills = skills + rs.getString(2) + ", ";
            }
            internDetails.setInternSkills(skills);
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        } 
    }//GEN-LAST:event_checkInternProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerCertifyInterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerCertifyInterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerCertifyInterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerCertifyInterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EmployerCertifyInterns().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton certifyIntern;
    private javax.swing.JButton checkInternProfile;
    private javax.swing.JTextField internName;
    private javax.swing.JComboBox<String> internRating;
    private javax.swing.JTextField internUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
