/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author INDIA
 */
public class SelectedInternProfile extends javax.swing.JFrame {

    /**
     * @param internAge the internAge to set
     */
    String username;
    String internshipID;
    
    ApplicantsList al;
    EmployerHome eh;

    public SelectedInternProfile(ApplicantsList al, EmployerHome eh) {
        initComponents();
        this.al = al;
        this.eh = eh;
        
        internAge.setDisabledTextColor(Color.GRAY);
        internContactNumber.setDisabledTextColor(Color.GRAY);
        internEmailId.setDisabledTextColor(Color.GRAY);
        internName.setDisabledTextColor(Color.GRAY);
        internQualification.setDisabledTextColor(Color.GRAY);
        internRating.setDisabledTextColor(Color.GRAY);
        internSkills.setDisabledTextColor(Color.GRAY);
        internUsername.setDisabledTextColor(Color.GRAY);
        
        setIconImage();
    }
    
    public void setInternAge(String Age) {
        internAge.setText(Age);
    }

    /**
     * @param internContactNumber the internContactNumber to set
     */
    public void setInternContactNumber(String ContactNumber) {
        internContactNumber.setText(ContactNumber);
    }

    /**
     * @param internEmailId the internEmailId to set
     */
    public void setInternEmailId(String EmailId) {
        internEmailId.setText(EmailId);
    }

    /**
     * @param internName the internName to set
     */
    public void setInternName(String Name) {
        internName.setText(Name);
    }

    /**
     * @param internQualification the internQualification to set
     */
    public void setInternQualification(String Qualification) {
        internQualification.setText(Qualification);
    }

    /**
     * @param internRating the internRating to set
     */
    public void setInternRating(String Rating) {
        internRating.setText(Rating);
    }

    /**
     * @param internSkills the internSkills to set
     */
    public void setInternSkills(String Skills) {
        internSkills.setText(Skills);
    }

    public void setInternshipId(String internshipId)
    {
        internshipID = internshipId;
    }
    
    /**
     * @param internUsername the internUsername to set
     */
    public void setInternUsername(String Username) {
        internUsername.setText(Username);
        username = Username;
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,Username);
            ResultSet rs = pstmt.executeQuery();
            internImage.setText("");
            while(rs.next())
            {
                Blob b = rs.getBlob(8);
                
		byte barr[]=b.getBytes(1,(int)b.length());
			              
		//FileOutputStream fout=new FileOutputStream("C:\\Users\\sravy\\Desktop\\book3.jpg");  
		//fout.write(barr); 
                ImageIcon icon = new ImageIcon(barr);
                //java.awt.Image image = icon.getImage().getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
                java.awt.Image img = icon.getImage();
                java.awt.Image scale = img.getScaledInstance(internImage.getWidth(), internImage.getHeight(),java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaled = new ImageIcon(scale);
                internImage.setIcon(scaled);   
                
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        internName = new javax.swing.JTextField();
        internContactNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        internEmailId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        internAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        internRating = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        internUsername = new javax.swing.JTextField();
        internQualification = new javax.swing.JTextField();
        internImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        internSkills = new javax.swing.JTextArea();
        closeInternProfileButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        selectIntern = new javax.swing.JButton();
        rejectIntern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(202, 223, 227));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interns's Profile");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 87, 94));
        jLabel8.setText("NAME                       :");

        internName.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internName.setForeground(new java.awt.Color(49, 87, 94));
        internName.setEnabled(false);
        internName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internNameActionPerformed(evt);
            }
        });

        internContactNumber.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internContactNumber.setForeground(new java.awt.Color(49, 87, 94));
        internContactNumber.setEnabled(false);
        internContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internContactNumberActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 87, 94));
        jLabel12.setText("CONTACT NUMBER         :");

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(49, 87, 94));
        jLabel14.setText("EMAIL ID                             :");

        internEmailId.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internEmailId.setForeground(new java.awt.Color(49, 87, 94));
        internEmailId.setEnabled(false);
        internEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internEmailIdActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 87, 94));
        jLabel9.setText("AGE                           :");

        internAge.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internAge.setForeground(new java.awt.Color(49, 87, 94));
        internAge.setEnabled(false);
        internAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internAgeActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 87, 94));
        jLabel11.setText("SKILLS                       :");

        internRating.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internRating.setForeground(new java.awt.Color(49, 87, 94));
        internRating.setEnabled(false);
        internRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internRatingActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 87, 94));
        jLabel6.setText("USERNAME              :");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 87, 94));
        jLabel10.setText("QUALIFICATION     :");

        internUsername.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internUsername.setForeground(new java.awt.Color(49, 87, 94));
        internUsername.setEnabled(false);
        internUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internUsernameActionPerformed(evt);
            }
        });

        internQualification.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internQualification.setForeground(new java.awt.Color(49, 87, 94));
        internQualification.setEnabled(false);
        internQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internQualificationActionPerformed(evt);
            }
        });

        internImage.setBackground(new java.awt.Color(255, 255, 255));
        internImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        internImage.setForeground(new java.awt.Color(49, 87, 94));
        internImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internImage.setText("IMAGE");
        internImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 87, 94)));

        internSkills.setColumns(20);
        internSkills.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        internSkills.setForeground(new java.awt.Color(49, 87, 94));
        internSkills.setRows(5);
        internSkills.setEnabled(false);
        jScrollPane1.setViewportView(internSkills);

        closeInternProfileButton.setBackground(new java.awt.Color(244, 139, 1));
        closeInternProfileButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        closeInternProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        closeInternProfileButton.setText("Close");
        closeInternProfileButton.setBorder(null);
        closeInternProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInternProfileButtonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 87, 94));
        jLabel13.setText("INTERN RATING     :");

        selectIntern.setBackground(new java.awt.Color(244, 139, 1));
        selectIntern.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        selectIntern.setForeground(new java.awt.Color(255, 255, 255));
        selectIntern.setText("SELECT");
        selectIntern.setBorder(null);
        selectIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInternActionPerformed(evt);
            }
        });

        rejectIntern.setBackground(new java.awt.Color(244, 139, 1));
        rejectIntern.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rejectIntern.setForeground(new java.awt.Color(255, 255, 255));
        rejectIntern.setText("REJECT");
        rejectIntern.setBorder(null);
        rejectIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectInternActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(selectIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(rejectIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(closeInternProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(internAge, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(internUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(internQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(internContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(64, 64, 64))
                                .addComponent(internEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(53, 53, 53))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeInternProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(internContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(internEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectIntern, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internNameActionPerformed

    private void internAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internAgeActionPerformed

    private void internRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internRatingActionPerformed

    private void internUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internUsernameActionPerformed

    private void internQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internQualificationActionPerformed

    private void internContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internContactNumberActionPerformed

    private void closeInternProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInternProfileButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeInternProfileButtonActionPerformed

    private void internEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internEmailIdActionPerformed
    
    private void selectInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInternActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("UPDATE INTERNSHIP_ENROLLED_INTERNS SET APPLICATIONSTATUS=? WHERE INTERNID=? AND INTERNSHIPID=?");
            pstmt.setString(1,"SELECTED");
            pstmt.setString(2, username);
            pstmt.setString(3, internshipID);
            int rs = pstmt.executeUpdate();
            if(rs > 0)
            {
                JOptionPane.showMessageDialog(this, "INTERN SELECTED !");
                dispose();
                al.setApplicantsDetails(internshipID);
                eh.refreshInternships();
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_selectInternActionPerformed

    private void rejectInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectInternActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  

            
            PreparedStatement pstmt = con.prepareStatement("UPDATE INTERNSHIP_ENROLLED_INTERNS SET APPLICATIONSTATUS=? WHERE INTERNID=? AND INTERNSHIPID=?");
            pstmt.setString(1,"REJECTED");
            pstmt.setString(2, username);
            pstmt.setString(3, internshipID);
            int rs = pstmt.executeUpdate();
            if(rs > 0)
            {
                JOptionPane.showMessageDialog(this, "INTERN REJECTED !");
                al.setApplicantsDetails(internshipID);
                eh.refreshInternships();
                dispose();
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        }
    }//GEN-LAST:event_rejectInternActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SelectedInternProfile().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeInternProfileButton;
    private javax.swing.JTextField internAge;
    private javax.swing.JTextField internContactNumber;
    private javax.swing.JTextField internEmailId;
    private javax.swing.JLabel internImage;
    private javax.swing.JTextField internName;
    private javax.swing.JTextField internQualification;
    private javax.swing.JTextField internRating;
    private javax.swing.JTextArea internSkills;
    private javax.swing.JTextField internUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectIntern;
    private javax.swing.JButton selectIntern;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
