/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internhire;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author INDIA
 */
public class ViewCertifyInternProfile extends javax.swing.JFrame {

    /**
     * @param internAge the internAge to set
     */
    String internId;
    
    public ViewCertifyInternProfile(String internId) {
        initComponents();
        this.internId = internId;
        
        internAge.setDisabledTextColor(Color.GRAY);
        internContactNumber.setDisabledTextColor(Color.GRAY);
        internEmailId.setDisabledTextColor(Color.GRAY);
        internName.setDisabledTextColor(Color.GRAY);
        internQualification.setDisabledTextColor(Color.GRAY);
        internRating.setDisabledTextColor(Color.GRAY);
        internSkills.setDisabledTextColor(Color.GRAY);
        internUsername.setDisabledTextColor(Color.GRAY);
        
        setIconImage();
    }
    
    public void setInternAge(String Age) {
        internAge.setText(Age);
    }

    /**
     * @param internContactNumber the internContactNumber to set
     */
    public void setInternContactNumber(String ContactNumber) {
        internContactNumber.setText(ContactNumber);
    }

    /**
     * @param internEmailId the internEmailId to set
     */
    public void setInternEmailId(String EmailId) {
        internEmailId.setText(EmailId);
    }

    /**
     * @param internName the internName to set
     */
    public void setInternName(String Name) {
        internName.setText(Name);
    }

    /**
     * @param internQualification the internQualification to set
     */
    public void setInternQualification(String Qualification) {
        internQualification.setText(Qualification);
    }

    /**
     * @param internRating the internRating to set
     */
    public void setInternRating(String Rating) {
        internRating.setText(Rating);
    }

    /**
     * @param internSkills the internSkills to set
     */
    public void setInternSkills(String Skills) {
        internSkills.setText(Skills);
    }

    /**
     * @param internUsername the internUsername to set
     */
    public void setInternUsername(String Username) {
        internUsername.setText(Username);
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");  

            Connection con=DriverManager.getConnection(  
            "jdbc:oracle:thin:@localhost:1521:xe","santosh","oracle");  
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM INTERN_DETAILS WHERE username = ?");
            pstmt.setString(1,Username);
            ResultSet rs = pstmt.executeQuery();
            internImage.setText("");
            while(rs.next())
            {
                Blob b = rs.getBlob(8);
                
		byte barr[]=b.getBytes(1,(int)b.length());
			              
		//FileOutputStream fout=new FileOutputStream("C:\\Users\\sravy\\Desktop\\book3.jpg");  
		//fout.write(barr); 
                ImageIcon icon = new ImageIcon(barr);
                //java.awt.Image image = icon.getImage().getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
                java.awt.Image img = icon.getImage();
                java.awt.Image scale = img.getScaledInstance(internImage.getWidth(), internImage.getHeight(),java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaled = new ImageIcon(scale);
                internImage.setIcon(scaled);   
                
            }
        con.close();  
        }
        catch(Exception e){ 
            System.out.println(e);
        } 
    }

    /**
     * Creates new form SelectedIntern
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        internName = new javax.swing.JTextField();
        internContactNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        internAge = new javax.swing.JTextField();
        internEmailId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        internRating = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        internSkills = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        internUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        internQualification = new javax.swing.JTextField();
        closeInternProfileButton = new javax.swing.JButton();
        internImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(202, 223, 227));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 87, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interns's Profile");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 87, 94));
        jLabel8.setText("NAME                       :");

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 87, 94));
        jLabel12.setText("CONTACT NUMBER         :");

        internName.setForeground(new java.awt.Color(49, 87, 94));
        internName.setEnabled(false);
        internName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internNameActionPerformed(evt);
            }
        });

        internContactNumber.setForeground(new java.awt.Color(49, 87, 94));
        internContactNumber.setEnabled(false);
        internContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internContactNumberActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 87, 94));
        jLabel9.setText("AGE                           :");

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(49, 87, 94));
        jLabel14.setText("EMAIL ID                             :");

        internAge.setForeground(new java.awt.Color(49, 87, 94));
        internAge.setEnabled(false);
        internAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internAgeActionPerformed(evt);
            }
        });

        internEmailId.setForeground(new java.awt.Color(49, 87, 94));
        internEmailId.setEnabled(false);
        internEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internEmailIdActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 87, 94));
        jLabel13.setText("INTERN RATING     :");

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 87, 94));
        jLabel11.setText("SKILLS                       :");

        internRating.setForeground(new java.awt.Color(49, 87, 94));
        internRating.setEnabled(false);
        internRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internRatingActionPerformed(evt);
            }
        });

        internSkills.setColumns(20);
        internSkills.setForeground(new java.awt.Color(49, 87, 94));
        internSkills.setRows(5);
        internSkills.setEnabled(false);
        jScrollPane1.setViewportView(internSkills);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 87, 94));
        jLabel6.setText("USERNAME              :");

        internUsername.setForeground(new java.awt.Color(49, 87, 94));
        internUsername.setEnabled(false);
        internUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internUsernameActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 87, 94));
        jLabel10.setText("QUALIFICATION     :");

        internQualification.setForeground(new java.awt.Color(49, 87, 94));
        internQualification.setEnabled(false);
        internQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internQualificationActionPerformed(evt);
            }
        });

        closeInternProfileButton.setBackground(new java.awt.Color(244, 139, 1));
        closeInternProfileButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        closeInternProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        closeInternProfileButton.setText("Close");
        closeInternProfileButton.setBorder(null);
        closeInternProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInternProfileButtonActionPerformed(evt);
            }
        });

        internImage.setBackground(new java.awt.Color(255, 255, 255));
        internImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        internImage.setForeground(new java.awt.Color(49, 87, 94));
        internImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internImage.setText("IMAGE");
        internImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 87, 94)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeInternProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(326, 326, 326))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(internUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(internQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(85, 85, 85))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(internAge, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(64, 64, 64))
                            .addComponent(internEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(internName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internContactNumber))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(internAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(internEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(internImage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jScrollPane1)))
                .addGap(36, 36, 36)
                .addComponent(closeInternProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internNameActionPerformed

    private void internAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internAgeActionPerformed

    private void internRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internRatingActionPerformed

    private void internUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internUsernameActionPerformed

    private void internQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internQualificationActionPerformed

    private void internContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internContactNumberActionPerformed

    private void closeInternProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInternProfileButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeInternProfileButtonActionPerformed

    private void internEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internEmailIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCertifyInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCertifyInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCertifyInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCertifyInternProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewCertifyInternProfile().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewCertifyInternProfile().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeInternProfileButton;
    private javax.swing.JTextField internAge;
    private javax.swing.JTextField internContactNumber;
    private javax.swing.JTextField internEmailId;
    private javax.swing.JLabel internImage;
    private javax.swing.JTextField internName;
    private javax.swing.JTextField internQualification;
    private javax.swing.JTextField internRating;
    private javax.swing.JTextArea internSkills;
    private javax.swing.JTextField internUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoIcon.PNG")));
    }
}
